# modified message of the day
[core]
output_color=true
template_path="$HOME/.config/mmotd/mmotd_template.json"

[fortune]
db_directory="$HOME/.config/mmotd"
file_name="softwareengineering"

[location]
timezone="America/Denver"
city="Lehi"
state="UT"
country="US"

[logging]
severity="trace"
